#!/bin/sh

#-
# Copyright 2014 Emmanuel Vadot <elbarto@bocal.org>
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions 
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

find_wlan() {
    wlan=`hwinfo --wlan --short | sed '1d' | awk '{print $1}' | head -n 1`

    echo ${wlan}
}

find_lans() {
    if [ -z "$1" ]; then
	lans=`hwinfo --netcard --short | sed '1d' | awk '{print $1}' | xargs echo`
    else
	lans=`hwinfo --netcard --short | grep -v $1 | sed '1d' | awk '{print $1}' | xargs echo`
    fi

    echo ${lans}
}

generate_wpa_supplicant_service() {
    device=$1
    sed "s/__DEVICE__/${device}/g" /usr/lib/systemd/system/wpa_supp.service.tpl > /usr/lib/systemd/system/wpa_supp.service
    cp /etc/wpa_supplicant/wpa_supplicant.conf.tpl /etc/wpa_supplicant/wpa_supplicant.conf
    /usr/bin/systemctl daemon-reload
    /usr/bin/systemctl disable wpa_supplicant.service
    /usr/bin/systemctl stop wpa_supplicant.service
    /usr/bin/systemctl enable wpa_supp.service
    /usr/bin/systemctl enable wpa_watch.service
    /usr/bin/systemctl start wpa_supp.service
    /usr/bin/systemctl start wpa_watch.service
}

generate_wlan_netcfg_file() {
    cat <<EOF
BOOTPROTO='dhcp4'
STARTMODE='ifplugd'
IFPLUGD_PRIORITY=1
DHCLIENT_SET_DEFAULT_ROUTE='yes'
DHCLIENT_USE_LAST_LEASE='no'
DHCLIENT_RELEASE_BEFORE_QUIT='yes'
DHCLIENT_PRIMARY_DEVICE='no'
EOF
}

generate_lan_netcfg_file() {
    cat <<EOF
BOOTPROTO='dhcp4'
STARTMODE='ifplugd'
IFPLUGD_PRIORITY=2
DHCLIENT_SET_DEFAULT_ROUTE='yes'
DHCLIENT_USE_LAST_LEASE='no'
DHCLIENT_RELEASE_BEFORE_QUIT='yes'
DHCLIENT_PRIMARY_DEVICE='yes'
EOF
}

wlan=`find_wlan`
lans=`find_lans ${wlan}`

if [ ! -z "${wlan}" ]; then
    echo "Found wlan device: ${wlan}"
    generate_wlan_netcfg_file > /etc/sysconfig/network/ifcfg-${wlan}
    generate_wpa_supplicant_service ${wlan}
fi

if [ ! -z "${lans}" ]; then
    echo "Found lan device(s): ${lans}"
    for lan in ${lans}; do
	generate_lan_netcfg_file > /etc/sysconfig/network/ifcfg-${lan}
    done
fi
