#!/bin/sh

find_wlan() {
    wlan=`hwinfo --wlan --short | sed '1d' | awk '{print $1}' | head -n 1`

    echo ${wlan}
}

find_lans() {
    if [ -z "$1" ]; then
	lans=`hwinfo --netcard --short | sed '1d' | awk '{print $1}' | xargs echo`
    else
	lans=`hwinfo --netcard --short | grep -v ${exclude} | sed '1d' | awk '{print $1}' | xargs echo`
    fi

    echo ${lans}
}

generate_wpa_supplicant_service() {
    device=$1
    sed "s/__DEVICE__/${device}/g" /usr/lib/systemd/system/wpa_supplicant.service.tpl > /usr/lib/systemd/system/wpa_supplicant.service
}

generate_wlan_netcfg_file() {
    cat <<EOF
BOOTPROTO='dhcp4'
STARTMODE='ifplugd'
IFPLUGD_PRIORITY=1
DHCLIENT_SET_DEFAULT_ROUTE='yes'
DHCLIENT_USE_LAST_LEASE='no'
DHCLIENT_RELEASE_BEFORE_QUIT='yes'
DHCLIENT_PRIMARY_DEVICE='no'
EOF
}

generate_lan_netcfg_file() {
    cat <<EOF
BOOTPROTO='dhcp4'
STARTMODE='ifplugd'
IFPLUGD_PRIORITY=2
DHCLIENT_SET_DEFAULT_ROUTE='yes'
DHCLIENT_USE_LAST_LEASE='no'
DHCLIENT_RELEASE_BEFORE_QUIT='yes'
DHCLIENT_PRIMARY_DEVICE='yes'
EOF
}

wlan=`find_wlan`
lans=`find_lans ${wlan}`

if [ ! -z "${wlan}" ]; then
    echo "Found wlan device: ${wlan}"
    generate_wlan_netcfg_file > /etc/sysconfig/network/ifcfg-${wlan}
    generate_wpa_supplicant_service ${wlan}
fi

if [ ! -z "${lans}" ]; then
    echo "Found lan device(s): ${lans}"
    for lan in ${lans}; do
	generate_lan_netcfg_file > /etc/sysconfig/network/ifcfg-${lan}
    done
fi
